# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a83615ea0e4773fcb1cc03ad3d2d3c2eda336392421b1586beaf75ff7edbb0a31ab42b2c9cc176e9a38ad5062fb95464223e0939ff828db905f23f6618327cd

test:
  secret_key_base: 11bf4beef27fd2edf2ff14a4c5f4c5aff08b386c56a4a08cbb6f944974f98c38517842df022c1513f042ea23c6d35d6472b59e305951b6dbedbe57a249948a38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
